# Generated by Django 6.0 on 2026-01-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/static/assets/img/gallary/1.png', null=True, upload_to='profile_pics/'),
        ),
    ]
