# Generated by Django 6.0 on 2026-01-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
    ]
